spring:
  flyway:
    locations: classpath:db/migration,classpath:db/data
    cleanDisabled: true
  datasource:
    name: LimitDataSource
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/limit-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: limitPool
      connection-test-query: select now()
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  jpa:
    open-in-view: true
#    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
